
[main]
	menu_keybind = true
	block_on_route_esp = true
	structure_finder = true
	render_pathbreak_helper = false
	add_block_to_list_keybind = true
	smoothlook = 3
	aotv_teleport_time = 118
	macro_spot = 0

[helper-mode]
	turn_on_helper = false

[fail-safes]
	player_failsafe = false
	player_esp_distance_ = 15
	player_esp = false
	distance = 50

[fun]
	block_esp_color_blue = 0
	block_esp_color_green = 0
	block_esp_color_red = 10

